"""Rift deterministic capstone documentation tooling."""

from .document_set import ArtifactCandidate, DocumentArtifact, DocumentSet, DocumentSetLoader
from .engine import ValidationEngine
from .validators.cross_document import CrossDocumentValidator
from .model import (
    Block,
    Cell,
    ContentClass,
    Document,
    Image,
    Section,
    Sheet,
    SourceLocation,
    Table,
    Workbook,
)
from .results import Finding, Status, ValidationResult
from .semantic import (
    EvidencePacket,
    EvidencePacketBuilder,
    FakeLLMProvider,
    LLMProvider,
    LLMProviderConfig,
    OpenAICompatibleProvider,
    PromptRenderer,
    SemanticAuditOptions,
    SemanticAuditReport,
    SemanticAuditRunner,
    SemanticConfidence,
    SemanticEvaluationCase,
    SemanticEvaluationHarness,
    SemanticEvaluationMetrics,
    SemanticEvaluationSet,
    SemanticEvidence,
    SemanticPlan,
    SemanticResult,
    SemanticResultCache,
    SemanticReviewPlanner,
    SemanticReviewTask,
    SemanticTaskType,
)
from .spec import CapstoneSpec, OrphanRule, SpecError, SpecValidationError, TraceRule, TraceTargetRule
from .trace_entities import TraceEntityExtractor
from .trace_model import MatchMethod, MatchResult, TraceEdge, TraceEntity, TraceGraph, TraceIndex, TraceLinkStatus, normalize_identifier, normalize_name

__all__ = [
    "ArtifactCandidate",
    "Block",
    "CapstoneSpec",
    "Cell",
    "ContentClass",
    "CrossDocumentValidator",
    "DocumentArtifact",
    "DocumentSet",
    "DocumentSetLoader",
    "Document",
    "EvidencePacket",
    "EvidencePacketBuilder",
    "FakeLLMProvider",
    "Finding",
    "LLMProvider",
    "LLMProviderConfig",
    "MatchMethod",
    "MatchResult",
    "Image",
    "Section",
    "Sheet",
    "SourceLocation",
    "OrphanRule",
    "OpenAICompatibleProvider",
    "PromptRenderer",
    "SemanticAuditOptions",
    "SemanticAuditReport",
    "SemanticAuditRunner",
    "SemanticConfidence",
    "SemanticEvaluationCase",
    "SemanticEvaluationHarness",
    "SemanticEvaluationMetrics",
    "SemanticEvaluationSet",
    "SemanticEvidence",
    "SemanticPlan",
    "SemanticResult",
    "SemanticResultCache",
    "SemanticReviewPlanner",
    "SemanticReviewTask",
    "SemanticTaskType",
    "Status",
    "Table",
    "TraceEdge",
    "TraceEntity",
    "TraceEntityExtractor",
    "TraceGraph",
    "TraceIndex",
    "TraceLinkStatus",
    "TraceRule",
    "TraceTargetRule",
    "ValidationEngine",
    "ValidationResult",
    "Workbook",
    "normalize_identifier",
    "normalize_name",
]
