# Uncomment this line to define a global platform for your project
# platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end

  pods_runner = installer.pods_project.targets.find { |target| target.name == 'Pods-Runner' }
  runner_aggregate = installer.aggregate_targets.find { |target| target.name == 'Pods-Runner' }
  if pods_runner && runner_aggregate
    runner_project = runner_aggregate.user_project
    pods_project_path = installer.pods_project.path.realpath
    unless runner_project.reference_for_path(pods_project_path)
      relative_path = pods_project_path.relative_path_from(runner_project.path.dirname)
      runner_project.main_group.new_file(relative_path)
    end

    runner = runner_project.targets.find { |target| target.name == 'Runner' }
    runner.add_dependency(pods_runner) if runner
    runner_project.save
  end
end
