<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.Versioning.SupportedOSPlatformAttribute">
      <_Parameter1>linux</_Parameter1>
    </AssemblyAttribute>
    <InternalsVisibleTo Include="Rift.Daemon.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ace4896.DBus.Services.Secrets" Version="1.6.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.10" />
    <PackageReference Include="StreamJsonRpc" Version="2.25.29" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.94.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rift.Daemon.Core\Rift.Daemon.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\rift-daemon.service" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
