name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Install dependencies
        run: flutter pub get
        working-directory: app-flutter
      - name: Analyze
        run: flutter analyze
        working-directory: app-flutter
      - name: Run tests
        run: flutter test --coverage
        working-directory: app-flutter

  daemon-dart-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Install dependencies
        run: flutter pub get
        working-directory: daemon-dart
      - name: Analyze
        run: dart analyze
        working-directory: daemon-dart
      - name: Run tests
        run: dart test
        working-directory: daemon-dart
